spring.application.name=billing-service

#Database connection settings
spring.datasource.url=jdbc:postgresql://postgres-db:5432/billing_db
spring.datasource.username=billing_user
spring.datasource.password=billing_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

#flyway settings(Enables database migrations)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
