spring.application.name=demo

#Database connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=billing_user
spring.datasource.password=billing_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#flyway settings(Enables database migrations)
spring.flyway.enabled=false
